"""vendor cap completeness

Revision ID: 0176a45f1dbb
Revises: 86c90c76a68f
Create Date: 2026-08-10 21:38:27.999656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0176a45f1dbb'
down_revision: Union[str, None] = '86c90c76a68f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_capabilities', sa.Column('completeness', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_capabilities', 'completeness')
    # ### end Alembic commands ###
