"""vendor cap doc_refs

Revision ID: 86c90c76a68f
Revises: 8e61a4676e6d
Create Date: 2026-08-10 21:34:36.238173

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '86c90c76a68f'
down_revision: Union[str, None] = '8e61a4676e6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vendor_capabilities', sa.Column('doc_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendor_capabilities', 'doc_refs')
    # ### end Alembic commands ###
